In [ ]:
# What does [10 + k for k in range(10) if k % 2 == 0] return?
# R: The values returned by the range iterator are filtered by the if condition, before adding 10 to each.


In [1]:
[10 + k for k in range(10) if k % 2 == 0]

[10, 12, 14, 16, 18]

In [ ]:
# Which values does range(5, 25, 5) iterate through?
# R: range(start, end, step) begins at "start", then continues to add "step" until it reaches "end" (which is not included in the output)


In [18]:
for amount in range(5, 25, 5):
    print(amount)

5
10
15
20


In [19]:
# What is the benefit of using comprehensions?
# R: shorter, more intuitive code that uses less memory
# Comprehensions can be shorter, use less memory, and may also be easier to understand.


In [ ]:
# Which range construct would generate the values 2,7,12, and 17?
# R: The range starts at 2 and increments by 5, until it is greater than or equal to 18.

In [20]:
for amount in range(2,18,5):
    print(amount)

2
7
12
17


In [ ]:
# Which of the following is NOT a common use of tuples in Python?

# R: As vectors of numbers that can be summed: for example, (1,2,3) + (4,5,6)
# Tuples do not support arithmetical operations. For that, a numpy array or a custom-designed class can be used.


In [ ]:
# What is one advantage of classes over named tuples?
# R: You can define methods for classes.
# You can make custom definitions of operations, such as addition. 


In [ ]:
# What is the difference between a list and a tuple?
# R: A tuple cannot be modified.
# Tuples are also defined with parentheses, but lists are defined with square brackets.


In [ ]:
# What does dict.items(), where dict is a Python dictionary, iterate over?
# R: All pairs (key, value) from the dictionary
# It is keys() that iterates over keys, and values() over values.


In [ ]:
# What is required for a dictionary key to be valid?
# R: It must be unique and hashable.


In [ ]:
# What does ["one", "two", "three"][-4] return?
# R: It throws the exception IndexError: list index out of range
# Counting from the end, index -4 does not exist in a list of length three.

In [21]:
["one", "two", "three"][-4]

IndexError: list index out of range

In [ ]:
## What is the difference between loading additional elements to a set as opposed to a list?
# R: You use add for a set and append for a list. The list is ordered; the set is not.
# `append` places an additional element at the end of an ordered list.


In [ ]:
# What is the main difference between the slow and fast anagram methods in the example?
# R: the use of a dictionary
# Matches with the same signature are found using dictionary keys.


In [ ]:
# What is the result of '&&'.join(sorted("ping")?

In [24]:
'&&'.join(sorted("ping"))

'g&&i&&n&&p'

In [ ]:
## Numpy arrays of numerical values are generally stored _____.
# R: as contiguous blocks of memory
# All values have the same size in memory, and are stored one after the other (by default, row after row).



In [ ]:
# What is the purpose of NumPy?
# R: to enable the use of arrays and permit compatibility with FORTRAN and C
# NumPy allows many fixed variable types useful for array definition.


In [ ]:
# Which of the following returns array([0. , 0.25, 0.5 , 0.75, 1. ])?
# R: np.linspace(start, end, len) returns "len" elements, equally spaced between "start" and "end" (included).


In [31]:
import numpy as np
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# If the string "Station To Station" is assigned to a record array field of dtype 'U6', what happens?
# R: The field stores the string 'Statio'.
# Values are truncated to the length of the field.


In [ ]:
# If a = np.array([0,1,3,5,7,11]), what is a[a > 3]?
# R: The condition is true for elements 5, 7, 11, which are then selected by numpy "fancy indexing"

In [37]:
a = np.array([0,1,3,5,7,11])
a[a > 3]

array([ 5,  7, 11])

In [ ]:
# An array has dimensions 1000,1000,1. Which specification is equivalent to array[850,750,0]?
# array[-150,-250,0]
# One is indexing backwards.

In [ ]:
# What array does np.ones((3,3)) * np.linspace(0,1,3) return?
# R: Broadcasting matches the last dimension of the two-dimensional array with the one-dimensional array, so each column is multiplied by a different number.


In [36]:
np.ones((3,3)) * np.linspace(0,1,3)

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [ ]:
# What is the advantage of using the NumPy version of mathematical functions, rather than the ordinary Python versions?
# R: The NumPy versions can operate on all elements of an array at once.
# You can write shorter code.

In [ ]:
# How can you avoid edge or end effects when using np.correlate?
# R: by specifying the key 'valid'
# This eliminates the effect of missing data before and after the sequence.


In [ ]:
# How does np.interp work?
# R: by linear interpolation
# It draws line segments through the existing data.


In [ ]:
# In addition to the actual data, what information is used by np.genfromtext?
# R: the width of each field, the name of each field, the data types, and the stripping option
# 